name: Auto Pull on Commit

on:
  push:
    branches:
      - development

jobs:
  auto_pull:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull changes
      run: git pull
