name: Auto Pull on Commit

on:
  push:
    branches:
      - deployment
  pull_request:
    branches:
      - deployment

jobs:
  auto_pull:
    runs-on: self-hosted

    - name: Pull changes
      run: git pull

    - name: Restart pm2
      run: pm2 restart all